//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoolServerApp.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblProject
    {
        [Key]
        public int Project_ID { get; set; }

        public string Project_Name { get; set; }
        public int User_Id { get; set; }
        public string Project_Address1 { get; set; }
        public string Project_Address2 { get; set; }
        public int Project_City { get; set; }
        public int Project_State { get; set; }
        public int Project_Size { get; set; }
        public string Client_Name { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblState tblState { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
