//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoolServerApp.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblTypeFilter
    {
        [Key]
        public int Property_ID { get; set; }
        public int SubCategory_ID { get; set; }
        public string Type_Name { get; set; }
        public string Type_Options { get; set; }
    
        public virtual tblProperty tblProperty { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
